### ISSUE TITLE
Code Release？

### ISSUE THREAD

**Issue by Jacky-H-uang** [fallingnight/PsPG#2]
Your research is so excellent, can you release the code？

**Comment by fallingnight** [comment]
sorry for our delay. 
these days we are still working on postgraduate applications, and haven't yet finished organizing the code (and comments, deployment guidelines). 
the code will be released no later than when we submit the camera-ready version.

**Comment by Ssslgend** [comment]
Traceback (most recent call last):
  File "F:\project\gitprojects\vscode\zsl\PsPG-1\train.py", line 251, in <module>
    main()
  File "F:\project\gitprojects\vscode\zsl\PsPG-1\train.py", line 190, in main
    train_loss, epoch_time, train_mAP = train_epoch(
  File "F:\project\gitprojects\vscode\zsl\PsPG-1\trainer.py", line 144, in train_epoch
    mAP_value, _ = calc_map(
  File "F:\project\gitprojects\vscode\zsl\PsPG-1\utils\metrics.py", line 208, in calc_map
    ap = calc_ap(gt_class, pred_class)
  File "F:\project\gitprojects\vscode\zsl\PsPG-1\utils\metrics.py", line 198, in calc_ap
    precision, recall, thresholds = precision_recall_curve(ground_truth, predictions)
  File "D:\Envs\pspg\lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper    
    return func(*args, **kwargs)
  File "D:\Envs\pspg\lib\site-packages\sklearn\metrics\_ranking.py", line 1002, in precision_recall_curve
    fps, tps, thresholds = _binary_clf_curve(
  File "D:\Envs\pspg\lib\site-packages\sklearn\metrics\_ranking.py", line 817, in _binary_clf_curve 
    raise ValueError("{0} format is not supported".format(y_type)) 你好我复现这个项目时为什么会出现这问题 calc_ap 输入怎么是多分类的格式
